import type { Severity } from "@/lib/database.types";

export interface RuleDef {
  id: string;
  name: string;
  category: string;
  severity: Severity;
  baseScore: number;
  description: string;
  recommendation: string;
  steps: string[];
  references: string[];
}

/**
 * The 26-rule Secrai catalog. This is the source of truth seeded into
 * `risk_rules` (see supabase/seed.sql — keep the two in sync).
 * The evaluation logic in map.ts decides which of these fire for a tenant
 * based on live Microsoft signals.
 */
export const RULES: RuleDef[] = [
  { id: "SEC-001", name: "MFA not enforced for privileged accounts", category: "Identity & Access", severity: "critical", baseScore: 95,
    description: "Administrative and privileged accounts can authenticate with a password alone, with no second factor.",
    recommendation: "Enforce phishing-resistant MFA (FIDO2/hardware keys) on all privileged and break-glass accounts.",
    steps: ["Inventory all privileged and service accounts", "Enroll admins in FIDO2/hardware-key MFA", "Require MFA for admin roles via Conditional Access", "Disable legacy authentication"],
    references: ["NIST 800-63B", "CIS Control 6.5"] },
  { id: "SEC-002", name: "Weak or compromised credentials", category: "Identity & Access", severity: "high", baseScore: 70,
    description: "Accounts show credential-risk indicators or a policy that permits weak passwords.",
    recommendation: "Require strong passphrases, block breached passwords, and remediate risky users.",
    steps: ["Enable breached-password protection", "Force reset on flagged risky users", "Require ≥14-character passphrases"],
    references: ["NIST 800-63B"] },
  { id: "SEC-003", name: "Inactive administrator accounts", category: "Identity & Access", severity: "high", baseScore: 68,
    description: "Enabled administrator accounts have had no sign-in activity for over 90 days.",
    recommendation: "Disable or remove dormant privileged accounts and tighten the leaver process.",
    steps: ["Disable dormant admin accounts", "Automate 60-day inactivity disablement", "Review offboarding workflow"],
    references: ["CIS Control 5.3"] },
  { id: "SEC-004", name: "Unsupported operating systems in use", category: "Endpoint Security", severity: "critical", baseScore: 88,
    description: "Devices run an operating system past end-of-life that no longer receives security updates.",
    recommendation: "Migrate or isolate end-of-life systems; apply compensating controls in the interim.",
    steps: ["Identify workloads on EOL hosts", "Plan migration to a supported OS", "Network-isolate EOL hosts until migrated"],
    references: ["CIS Control 2.2"] },
  { id: "SEC-005", name: "Missing endpoint protection", category: "Endpoint Security", severity: "high", baseScore: 72,
    description: "Managed devices are not onboarded to endpoint detection and response.",
    recommendation: "Ensure full EDR coverage across all managed endpoints with health monitoring.",
    steps: ["Onboard non-reporting endpoints", "Enable agent-health alerting", "Block network access for non-compliant devices"],
    references: ["CIS Control 10"] },
  { id: "SEC-006", name: "Critical vulnerabilities detected", category: "Vulnerability Mgmt", severity: "critical", baseScore: 92,
    description: "Assets carry vulnerabilities with critical severity, some with public exploit code.",
    recommendation: "Prioritise remediation of exploitable critical CVEs within an emergency-patch SLA.",
    steps: ["Patch actively-exploited CVEs immediately", "Schedule remaining criticals within 7-day SLA", "Monitor exploited CVEs continuously"],
    references: ["CISA KEV", "CIS Control 7"] },
  { id: "SEC-007", name: "Backups not encrypted", category: "Backup & Recovery", severity: "high", baseScore: 74,
    description: "Backups are stored without encryption at rest.",
    recommendation: "Encrypt all backups at rest and manage keys in a dedicated KMS.",
    steps: ["Enable AES-256 on backup targets", "Move keys into managed KMS", "Verify restore from an encrypted backup"],
    references: ["CIS Control 11.3"] },
  { id: "SEC-008", name: "No tested disaster-recovery plan", category: "Backup & Recovery", severity: "high", baseScore: 66,
    description: "A disaster-recovery plan has never been tested with a live restore.",
    recommendation: "Run and document a full DR test at least annually; define RTO/RPO.",
    steps: ["Define RTO/RPO for tier-1 systems", "Execute a tabletop then a live restore", "Document and remediate gaps"],
    references: ["ISO 27001 A.17"] },
  { id: "SEC-009", name: "Publicly exposed administrative services", category: "Network Security", severity: "critical", baseScore: 90,
    description: "Administrative services are reachable directly from the public internet.",
    recommendation: "Remove direct exposure; place admin access behind VPN/ZTNA with MFA.",
    steps: ["Close public admin ports", "Route admin access through ZTNA", "Add geo and MFA conditional access"],
    references: ["CIS Control 4.6"] },
  { id: "SEC-010", name: "Email threats and missing authentication controls", category: "Email Security", severity: "high", baseScore: 64,
    description: "Phishing or malware is reaching mailboxes, or domain email authentication is weak.",
    recommendation: "Progress DMARC to reject, align SPF/DKIM, and tune anti-phishing policies.",
    steps: ["Enable DKIM signing on all senders", "Tighten SPF and set DMARC p=reject", "Tune Defender for Office anti-phishing"],
    references: ["M3AAWG Best Practices"] },
  { id: "SEC-011", name: "Unpatched critical systems", category: "Vulnerability Mgmt", severity: "high", baseScore: 78,
    description: "Software update recommendations for critical components remain unremediated.",
    recommendation: "Bring systems within a 14-day patch SLA driven by TVM recommendations.",
    steps: ["Action top software-update recommendations", "Automate patch windows", "Report SLA compliance monthly"],
    references: ["CIS Control 7.4"] },
  { id: "SEC-012", name: "Excessive administrator privileges", category: "Identity & Access", severity: "medium", baseScore: 58,
    description: "The share of users holding standing admin rights exceeds least-privilege targets.",
    recommendation: "Reduce standing privilege; adopt just-in-time elevation.",
    steps: ["Revoke unneeded admin grants", "Adopt just-in-time elevation (PIM)", "Quarterly access recertification"],
    references: ["CIS Control 6.8"] },
  { id: "SEC-013", name: "No centralized security logging", category: "Incident Response", severity: "medium", baseScore: 60,
    description: "Security events are not aggregated to a central SIEM.",
    recommendation: "Centralise logs to a SIEM with 12-month retention and alerting.",
    steps: ["Forward endpoint, identity and cloud logs", "Define priority detections", "Set 12-month retention"],
    references: ["CIS Control 8"] },
  { id: "SEC-014", name: "No incident-response plan", category: "Incident Response", severity: "high", baseScore: 70,
    description: "There is no documented, role-assigned incident-response plan.",
    recommendation: "Establish an IR plan with roles, severities and escalation paths.",
    steps: ["Draft an IR policy and severity matrix", "Assign roles and a contact tree", "Run a tabletop exercise"],
    references: ["NIST 800-61"] },
  { id: "SEC-015", name: "No security-awareness training", category: "Security Awareness", severity: "medium", baseScore: 54,
    description: "Staff have not completed security-awareness training recently.",
    recommendation: "Roll out mandatory annual training and phishing simulations.",
    steps: ["Assign mandatory annual training", "Launch quarterly phishing simulations", "Track completion to 95%+"],
    references: ["CIS Control 14"] },
  { id: "SEC-016", name: "Unencrypted sensitive data", category: "Data Protection", severity: "critical", baseScore: 86,
    description: "Sensitive data is stored without encryption at rest.",
    recommendation: "Encrypt sensitive data at rest and enforce key rotation.",
    steps: ["Enable TDE / column encryption", "Rotate and vault keys", "Confirm encryption in backups"],
    references: ["GDPR Art.32", "CIS Control 3.11"] },
  { id: "SEC-017", name: "Unsecured cloud storage", category: "Cloud Security", severity: "high", baseScore: 80,
    description: "Object storage permits unauthenticated public access.",
    recommendation: "Remove public access and enforce encryption and logging.",
    steps: ["Block public ACLs", "Enable default encryption", "Turn on access logging & alerts"],
    references: ["CIS Cloud Benchmark"] },
  { id: "SEC-018", name: "Missing network segmentation", category: "Network Security", severity: "medium", baseScore: 62,
    description: "Production, corporate and guest traffic share a flat network.",
    recommendation: "Segment networks by trust zone and restrict east-west traffic.",
    steps: ["Define trust zones", "Apply VLAN/firewall segmentation", "Micro-segment east-west traffic"],
    references: ["CIS Control 12"] },
  { id: "SEC-019", name: "Weak remote-access controls", category: "Network Security", severity: "high", baseScore: 68,
    description: "Legacy authentication or non-MFA remote access is in use.",
    recommendation: "Block legacy auth and require MFA on all remote access.",
    steps: ["Block legacy authentication via Conditional Access", "Enforce MFA on all remote access", "Migrate toward ZTNA"],
    references: ["CIS Control 12.7"] },
  { id: "SEC-020", name: "No vulnerability-scanning process", category: "Vulnerability Mgmt", severity: "medium", baseScore: 56,
    description: "There is no recurring authenticated vulnerability scanning.",
    recommendation: "Establish authenticated weekly scanning with tracked remediation.",
    steps: ["Deploy authenticated scanning", "Schedule weekly scans", "Track findings to closure"],
    references: ["CIS Control 7.1"] },
  { id: "SEC-021", name: "Expired security certificates", category: "Data Protection", severity: "medium", baseScore: 50,
    description: "TLS certificates on services have expired.",
    recommendation: "Renew certificates and automate lifecycle management.",
    steps: ["Renew expired certificates", "Automate issuance (ACME)", "Add expiry monitoring"],
    references: ["CIS Control 3"] },
  { id: "SEC-022", name: "Third-party access not reviewed", category: "Third-Party Risk", severity: "medium", baseScore: 58,
    description: "Vendor and contractor accounts have not been access-reviewed in over a year.",
    recommendation: "Recertify third-party access and enforce time-bound accounts.",
    steps: ["Recertify vendor accounts", "Set expiry on contractor access", "Formalise vendor-risk assessments"],
    references: ["CIS Control 15"] },
  { id: "SEC-023", name: "Shared user accounts in use", category: "Identity & Access", severity: "high", baseScore: 66,
    description: "Accounts are shared by multiple staff, breaking accountability.",
    recommendation: "Replace shared accounts with individual identities and privileged vaulting.",
    steps: ["Retire shared accounts", "Issue individual credentials", "Vault required service credentials"],
    references: ["CIS Control 5.2"] },
  { id: "SEC-024", name: "Missing account-lockout / brute-force protection", category: "Identity & Access", severity: "medium", baseScore: 52,
    description: "A high volume of failed sign-ins indicates weak brute-force protection.",
    recommendation: "Enable smart lockout and alert on repeated failures.",
    steps: ["Configure smart lockout", "Rate-limit auth endpoints", "Alert on brute-force patterns"],
    references: ["CIS Control 6"] },
  { id: "SEC-025", name: "No regular backup testing", category: "Backup & Recovery", severity: "medium", baseScore: 52,
    description: "Backups are taken but restores are not routinely tested.",
    recommendation: "Schedule and log recurring restore tests.",
    steps: ["Schedule monthly restore verification", "Log restore success", "Alert on backup failures"],
    references: ["ISO 27001 A.12.3"] },
  { id: "SEC-026", name: "Excessive external attack surface", category: "Network Security", severity: "high", baseScore: 76,
    description: "More internet-exposed services exist than are documented or required.",
    recommendation: "Reduce and continuously monitor the external attack surface.",
    steps: ["Inventory external-facing services", "Decommission unnecessary exposure", "Adopt attack-surface monitoring"],
    references: ["CIS Control 12.4"] },
];

export const ruleById = (id: string): RuleDef | undefined => RULES.find((r) => r.id === id);
